spring.application.name=InternalWorkingSpringBoot
spring.output.ansi.enabled=ALWAYS

# PostgreSQL Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_DB
#spring.datasource.username=postgres
#spring.datasource.password=java
#
#
## JPA Settings
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## PostgreSQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Update Context Path
server.servlet.context-path=/api

#Database Configration Mysql : mysql
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_management_syastem
spring.datasource.username=root
spring.datasource.password=Harsh@9595
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 #JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#server.servlet.context-path=/api

jwt.secretKey=hjkuiuertydfghayruitrhgkiuioe7845965hjsuietanhsjaknmjcklsahjk
app.refreshTokenExpiration=604800000
#Spring-Security Config
#spring.security.user.name=harsh
#spring.security.user.password=java

